### ISSUE TITLE
Flow description is not exported

### ISSUE THREAD

**Issue by fcastill** [TIBCOSoftware/flogo-web#604]
Original issue: TIBCOSoftware/flogo#96

```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
Exporting an app doesn't export the flow description.

**Expected behavior**
Flow description should be part of the exported json file.

**Minimal reproduction of the problem with instructions**
1. Create an app
2. Add a new flow
3. Set a description for the flow
4. Export the app
5. Observer the exported json, the description is not present

* **Flogo version:** v0.5.0

* **Browser:** all

## Tasks
- [x] Verify export app
- [x] Check export flows
- [x] Check export apps for devices

Original estimate: 6hrs
