### ISSUE TITLE
Modifying 'Flow params' results in invisible Flow configurations

### ISSUE THREAD

**Issue by fcastill** [TIBCOSoftware/flogo-web#606]
From TIBCOSoftware/flogo#102

## Tasks 
- [x] When the flow schema is modified any broken mapping needs to be removed - 3hrs
- [x] Create unit test case - 3hrs
- [x] Test when renaming the inputs of the flow all the trigger mappings are correctly updated (dangling mappings are removed) - 1hr
- [x] Testing with respect to run a flow without reloading the window nor going back to another screen - 2hr
