### ISSUE TITLE
Request: Display version number in Web UI

### ISSUE THREAD

**Issue by fcastill** [TIBCOSoftware/flogo-web#704]
From TIBCOSoftware/flogo-contrib#227

> could you please add the Flogo version number into the Web UI?
> I guess it would help both the users and the team to know on which versions people are working on...

We can display the tag that was used to build the flogo image. Ex: `v0.5.1`, `v0.5.2`.
Given our current build setup we can assume that flogo-cli, flogo-lib and flogo-contrib will match that version.

Visual spec:
https://zpl.io/2yBpDxG
[zpl://screen?sid=5aba89ddab55cf305294c8d0&pid=5aa9853b9b24ff5146920c5f](zpl://screen?sid=5aba89ddab55cf305294c8d0&pid=5aa9853b9b24ff5146920c5f)

## Tasks
- [x] Visual specs and copy
- [ ] Load the version into the UI during build time (Can be part of angular environment file)
- [x] Display version number in the UI
