### ISSUE TITLE
Support for mapper functions

### ISSUE THREAD

**Issue by fcastill** [TIBCOSoftware/flogo-web#705]
## Tasks

- [x] IxD/VxD specs
- [x] Update UI parser to accept functions
- [x] Ambiguity of `foo` expression being a string literal or an assignment needs to be resolved (type 1/assign vs type 2/literal)
- [x] Display functions in the UI <-- list of functions need to be provided (by who?)
- [x] Click on function should add it to the current editing expression
- [x] Function help in the editor (TIBCOSoftware/flogo-contrib#224)
