### ISSUE TITLE
New visual treatment for trigger configuration

### ISSUE THREAD

**Issue by fcastill** [TIBCOSoftware/flogo-web#714]
- [ ] IxD and VxD specs
- [ ] Apply new treatment

We maintain `714-trigger-config/base` as base branch for this epic and merge our changes to this branch. We can do one pull request to merge `714-trigger-config/base` to master once everything is developed.

**Dividing in to the following subtasks:** 

- [x] #759 - Make the current left hand side tabs to move to the top as horizontal sub tabs
      <img height= "150" width="500" src="https://user-images.githubusercontent.com/23206463/39171347-12263324-47bc-11e8-9480-ee7b13006101.png" />

- [x] Maintain dirty / dirty+erroneous states of the triggers and saving the changes should change all the modified triggers. Disable save when the modified triggers have erroneous mappings or configurations

- [x] Display triggers and represent dirty / dirty+erroneous states of the triggers - May 7th

- [x] #766 - Fetching triggers + handlers and saving changes - May 7th

- [x] #756 - Animate the triggers panel to expand and collapse while user try to `configure` the trigger's properties with flow's `inputs and outputs`. something like : https://angular-ql7xd8.stackblitz.io/
      <img height= "150" width="500" src="https://user-images.githubusercontent.com/23206463/39171538-c84e8e30-47bc-11e8-9da8-e0b8e5becda4.png" /> - May 8th
- [ ] Testing - May 8th
