### ISSUE TITLE
Support for syntax `$.propertyName` for trigger mappings

### ISSUE THREAD

**Issue by fcastill** [TIBCOSoftware/flogo-web#729]
Trigger mappings references of flow input/output should be generated using the `$.` prefix and imported trigger mappings should be updated to use the `$.` prefix.

## Examples
<img width="973" alt="screen shot 2018-03-27 at 11 25 34 am" src="https://user-images.githubusercontent.com/17577698/37986966-d1f213a6-31b1-11e8-9e45-210f907cf19a.png">

Expected serialized mapping:
```js
{
  "type": "assign",
  "mapTo": "input",
  "value": "$.content"
}
````

<img width="976" alt="screen shot 2018-03-27 at 11 26 04 am" src="https://user-images.githubusercontent.com/17577698/37987017-f0d6ab6a-31b1-11e8-88fc-3fc3a6d0476e.png">

```js
{
  "type": "assign",
  "mapTo": "code",
  "value": "$.output"
}
````

## Mapping samples

Assign
```js
{
  "type": "assign",
  "mapTo": "flowInput",
  "value": "$.triggerOutput"
}
```

Expression
```js
{
  "type": "expression",
  "mapTo": "flowInput",
  "value": "string.concat($.triggerOutput, \"foo\")"
}
```

Object
```js
{
  "type": "object",
  "mapTo": "flowInput",
  "value":  {
     "foo": "{{  $.triggerInput }}"
   }
}
```

## Tasks

- [x] Update parser to support current scope resolver `$.`
- [x] When generating mapping expressions for trigger mappings, when mapping flow inputs references to trigger output should be prefixed with `$.`
- [x] When generating mapping expressions for trigger mappings, when mapping trigger repply references to flow output should be prefixed with `$.`
- [ ] When app is imported trigger mappings of type "assign" should be "fixed" to use the `$.` prefix 
- [ ] When app is imported trigger mappings of type "expression" should be "fixed" to use the `$.` prefix
- [ ] When app is imported trigger mappings of type "object" should be "fixed" to use the `$.` prefix  <--- this one requires more work, our parser doesn't support parsing the values of object mappings string values (`"{{ outputName.x.y  }}"` -> `"{{ $.outputName.x.y  }}"`)
