### ISSUE TITLE
Remove Device profile from the application - client side

### ISSUE THREAD

**Issue by ylakkaku** [TIBCOSoftware/flogo-web#936]
Removing Device profile from the application in client side.

- [x] Prevent adding a Device profile manually from Application. - [ #940  ]
- [x] Remove all styles related to device profile from main.less - [ #951 ]
- [x] Remove profile type dependency in the state.  [ #942 ]
- [x] Remove profile type dependency in preparing the Client side application state  (UI converter model)- [ #942 ] 
- [x] Make API calls from services independent of application profile-  [ #942 ]
- [x] Remove device profile from home page (New application + application list)-  [ #942 ]
- [x] Remove device profile from application details page -  [ #942 ]
- [x] Remove device profile from flow designer page -  [ #942 ]
- [x] Remove device profile from mocks (if any) -  [ #942 ]
- [x] Remove unused code/ files and icons. - [ #947 ]
