### ISSUE TITLE
Epic: Support new engine v0.9.0

### ISSUE THREAD

**Issue by fcastill** [TIBCOSoftware/flogo-web#937]
Support the changes in the engine model v0.9.0 as well the repository organization.

 - [x] Update creation of engine to reference new repos (server) [ #992 ]
 - [x] Update internal references to contributions for new repos (subflow, return, etc.) (server) [ #1004 ]
 - [x] Update internal references to contributions for new repos (subflow, return, etc.) (client) [ #1005 ]
 - [x] Unify the old github paths of special contributions with the new github paths (server) [ #1006 ]
 - [x] Update creation and handling of default list of contributions (default palette) (server) [ #992 ]
 - [x] Add functions as contributions under the default list of contributions (server) [ #1008 ]
 - [x] Update contributions to support "descriptor.json" instead of activity.json and trigger.json (server) [ #992 ]
 - [x] Update import process to normalize new task.input syntax (server)[ #956 ]
 - [x] Support new task.input mappings syntax (client) [ #955 ]
 - [x] Support new syntax for settings (client) [ #978 ]
 - [x] Support new syntax for settings - import (server) [ #978 ]
~- [ ] Update export process to normalize new task.input syntax (server)~
 - [x] Support activity types and activity refs (flogo.json::imports) (server (and client?)) [ #979 ]
 - [x] Support for aliases in imports (server (and client?))
 - [x] Keep imports aliases during app import/export (server)
 - [x] Install/update contribution based functions (server) [ #1008 ]
 - [x] List contribution based functions (Mocked) (Engine loading and REST API) (server) [ #966 ]
 - [x] Display contribution based functions (client) [#966] 
 - [x] Merging input and input mappings: backwards compatibility (server (and client?)) [ #955 ]
 - [x] Support for activity settings (server) [ #980 ]
 - [x] Support for activity settings (client) [ #980 ]
 - [x] Activity settings should use the new syntax(server & client) [ #978 ]
 - [x] Replace godep with go modules (server)
 ~- [ ] Docker images dependency (cicd)~
 ~- [ ] Upgrade the go version in **production** docker images to v1.11+ (cicd)~
~-  [ ]  Setup database migration (server)~
-  [x]  Disable step debugging if it is not going to work with v0.9.0 application model(client (&server?)) [ #1009 ]
 - [x] Add a service which can be injected which maps the repository path of a contribution to `type` name (used while exporting the application) (server)
~- [ ] While importing a legacy application (v0.5.8 application) we need to validate if a function used is installed in the engine or not~ <--- Tracking it as part of #1078
- [x] New format to resolve the iteration key and value of an iterable task [ #1030 ]

**Bugs**

- [x] The new v0.9.0 application model is not imported properly [ #985 ]
- [x] Importing v0.5.7 application model ignores the trigger handler mappings due to JSON schema definition [ #982 ]
- [x] The Binary has runtime error when we use functions in mappings [ #1000 ]
- [x] Need to remove the temporary exception handling in flogo list [ #993 ]
- [x] Special activities are not working as expected [ #996 ]
- [x] Unable to build an application for cross compile options [ #1003 ]
