### ISSUE TITLE
Remove device profile in server side application

### ISSUE THREAD

**Issue by apandura-tibco** [TIBCOSoftware/flogo-web#939]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X] support request
```

**Current behavior**
Devices are supported in web ui. User can import, export, get list of contributions, install a contribution, create a device application.

**Expected behavior**
From v0.9.0 we are dropping the support to device profiles in web ui. The changes which can be included in this ticket are :

- [x] Remove device related endpoints [ #946 ]
- [x] Remove device related schemas [ #949 ]
- [x] Remove installing device contributions / loading contributions in server startup [ #946 ]
- [x] Remove profile type judgement in the application import [ #941 ]
- [x] Remove profile type manipulations in the application export [ #943 ]
