### ISSUE TITLE
Support new syntax for "settings" properties in the application descriptor

### ISSUE THREAD

**Issue by apandura-tibco** [TIBCOSoftware/flogo-web#978]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request
```

After implementing the new syntax for mappings, we have a query whether the "settings" properties need to follow the new syntax in case the value has a property or environment reference.

The "settings" can be any of the following:

- [x] 1. Trigger settings which are configurable in trigger configurator (Trigger Settings tab) [ #1007 ]
- [x] 2. Handler settings which are configurable in trigger configurator (Trigger Settings tab) [ #1007 ]
- [x] 3. Task's iterate value which are configurable in task configurator (Iterator tab) [ #1007 ]
- [x] 4. Task's settings which are configurable in task configurator (New tab, yet to be implemented ) 
- ~5. (May be) Link condition which are configurable in branch configurator~ Not needed as engine is not supporting it yet
