### ISSUE TITLE
Support for task settings based on activity schema

### ISSUE THREAD

**Issue by apandura-tibco** [TIBCOSoftware/flogo-web#980]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request
```
As described in [here](https://docs.google.com/document/d/1m9XE2Y2av3PfpzYWH6RPAsyIsyw54-J4kzXRwWyi_5U/edit#heading=h.en75kz8smtu7), the activity descriptors are going to have a new property `settings`. We need to follow the [wireframe](https://drive.google.com/open?id=10RPNewxn92OpIs-4XHVLPfqOvbTIWjo1) to add a new tab

- [x] Add the `settings` tab for normal activities in task configurator  [ #991 ]
- [x] Add the `activitySettings` (TBC) in the internal task descriptors for storing the values for them [ #991 ]
- [x] Normalize the task descriptor to maintain `resources[].data.tasks[].activity.setting` to `actions[].tasks[].activitySettings` while importing the application
- [x] Normalize the task descriptor to maintain `actions[].tasks[].activitySettings` to `resources[].data.tasks[].activity.setting` while exporting the application
- [ ] Normalize the activity schema to maintain settings in case an activity contribution does not have one
- [x] Special consideration for special type of activities [#996]
